# Generated by Django 5.0.6 on 2024-07-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='liquidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='volatility',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='liquidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stockpricehistory',
            name='volatility',
            field=models.FloatField(default=0.0),
        ),
    ]
