# Generated by Django 4.2.13 on 2024-07-17 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0003_alter_simulationsettings_interval_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='scenario',
        ),
        migrations.AddField(
            model_name='simulationsettings',
            name='stock_trading_logic',
            field=models.CharField(choices=[('dynamic', 'Dynamic'), ('static', 'Static')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='scenario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulation.scenario'),
        ),
        migrations.AlterField(
            model_name='simulationsettings',
            name='interval_unit',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='minute', max_length=6),
        ),
        migrations.AlterField(
            model_name='simulationsettings',
            name='timer_step_unit',
            field=models.CharField(choices=[('second', 'Second'), ('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('month', 'Month'), ('year', 'Year')], default='minute', max_length=6),
        ),
    ]
