services:
  django:
    build: .
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - minio
      - db
      - ollama
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    profiles:
      - web
      - all
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network
    profiles:
      - caching
      - other
      - all
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9000:9000"  # Main MinIO API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
    networks:
      - app-network
    profiles:
      - storage
      - other
      - all
      - minio
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio-client:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 ${MINIO_ACCESS_KEY:-minioadmin} ${MINIO_SECRET_KEY:-minioadmin}); do sleep 5; done;
      # Check if the media bucket exists; if not, create it
      /usr/bin/mc ls local/${MINIO_STORAGE_MEDIA_BUCKET_NAME:-media} || /usr/bin/mc mb local/${MINIO_STORAGE_MEDIA_BUCKET_NAME:-media};
      # Check if the static bucket exists; if not, create it
      /usr/bin/mc ls local/${MINIO_STORAGE_STATIC_BUCKET_NAME:-static} || /usr/bin/mc mb local/${MINIO_STORAGE_STATIC_BUCKET_NAME:-static};
      # Set the policy to public for the media bucket
      /usr/bin/mc policy set public local/${MINIO_STORAGE_MEDIA_BUCKET_NAME:-media};
      # Set the policy to public for the static bucket
      /usr/bin/mc policy set public local/${MINIO_STORAGE_STATIC_BUCKET_NAME:-static};
      "
    profiles:
      - all
      - other
      - minio
      - storage
    networks:
      - app-network


  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    ports:
      - "5432:5432"
    networks:
      - app-network
    profiles:
      - database
      - other
      - all
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  celery:
    build: .
    command: celery -A simulateur worker -l info
    volumes:
      - .:/workspace
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app-network
    profiles:
      - all
      - celery
      - other
    healthcheck:
      test: ["CMD-SHELL", "celery -A simulateur status"]
      interval: 30s
      timeout: 10s
      retries: 3

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    container_name: ollama
    profiles:
      - all
      - ollama
    pull_policy: always
    tty: true
    restart: always
    entrypoint: [ "/usr/bin/bash", "/entrypoint.sh" ]

volumes:
  minio_data:
  postgres_data:

networks:
  app-network:
    driver: bridge