version: '3.8'

services:
  django:
    build: .
    command: sh -c "python manage.py migrate && daphne simulateur.asgi:application -b 0.0.0.0 -p 8000"
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - ollama
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - OLLAMA_API_URL=http://ollama:11434
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.crt:/etc/nginx/nginx.crt
      - ./nginx.key:/etc/nginx/nginx.key
    depends_on:
      - django
    networks:
      - app-network

volumes:
  ollama:

networks:
  app-network:
