services:
  django:
    build: .
    command: >
      sh -c "python run.py --start-simulation 1"
    volumes:
      - .:/workspace
    depends_on:
      - redis
      - minio
      - influxdb
      - db
      - timescaledb
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OLLAMA_API_URL=http://ollama:11434
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN:-my-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-my-org}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-my-bucket}
      - TIMESCALEDB_URL=postgres://postgres:password@timescaledb:5432/postgres
    networks:
      - app-network
    profiles:
      - web
      - all
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network
    profiles:
      - caching
      - all
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
    ports:
      - "9002:9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    profiles:
      - storage
      - all
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    networks:
      - app-network
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-mydb}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-admin}
      - INFLUXDB_USER=${INFLUXDB_USER:-user}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-password}
    profiles:
      - metrics
      - all
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8086/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    profiles:
      - database
      - all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  timescaledb:
    image: timescale/timescaledb:latest-pg13
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - app-network
    profiles:
      - timeseriesdb
      - all
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  minio_data:
  postgres_data:
  timescaledb_data:

networks:
  app-network:
